spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/how2j/springcloudConfig/
          search-paths: respo

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




#  有时候，微服务要做集群，这就意味着，会有多个微服务实例。 在业务上有时候需要修改一些配置信息，比如说 版本信息吧~ 倘若没有配置服务， 那么就需要挨个修改微服务，挨个重新部署微服务，这样就比较麻烦。
#  为了偷懒， 这些配置信息就会放在一个公共的地方，比如git, 然后通过配置服务器把它获取下来，然后微服务再从配置服务器上取下来。
#  这样只要修改git上的信息，那么同一个集群里的所有微服务都立即获取相应信息了，这样就大大节约了开发，上线和重新部署的时间了。
#
#  如图所示，我们先在 git 里保存 version 信息， 然后通过 ConfigServer 去获取 version 信息， 接着不同的视图微服务实例再去 ConfigServer 里获取 version.


#  首先要准备git。
#如下是已经准备好的 git:
#  https://github.com/how2j/springcloudConfig/blob/master/respo/product-view-service-feign-dev.properties
#  这里就准备了版本信息： version = how2j springcloud version 1.0


#  先启动 EurekaServerApplication， 再启动 ConfigServerApplication， 然后访问
#  http://localhost:8020/version/dev
#  看到如图所示，就表示配置服务器准备好了